# Copyright 2019 Bertrand Lefort. All rights reserved.
# Use of this source code is governed under MIT License
# that can be found in the LICENSE file.
sudo: false
language: go

go:
- 1.11.x
- 1.12.x

before_install:
  - go get -t -v ./...

script:
  - ./test.sh

#after_success:
  - bash <(curl -s https://codecov.io/bash)